/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AddressFamily = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 21 | 22 | 23 | 24 | 25 | 26 | 28 | 29 | 65536 | 65537 | -1;

export const AddressFamily = {
    NUMBER_0: 0 as AddressFamily,
    NUMBER_1: 1 as AddressFamily,
    NUMBER_2: 2 as AddressFamily,
    NUMBER_3: 3 as AddressFamily,
    NUMBER_4: 4 as AddressFamily,
    NUMBER_5: 5 as AddressFamily,
    NUMBER_6: 6 as AddressFamily,
    NUMBER_7: 7 as AddressFamily,
    NUMBER_8: 8 as AddressFamily,
    NUMBER_9: 9 as AddressFamily,
    NUMBER_10: 10 as AddressFamily,
    NUMBER_11: 11 as AddressFamily,
    NUMBER_12: 12 as AddressFamily,
    NUMBER_13: 13 as AddressFamily,
    NUMBER_14: 14 as AddressFamily,
    NUMBER_15: 15 as AddressFamily,
    NUMBER_16: 16 as AddressFamily,
    NUMBER_17: 17 as AddressFamily,
    NUMBER_18: 18 as AddressFamily,
    NUMBER_19: 19 as AddressFamily,
    NUMBER_21: 21 as AddressFamily,
    NUMBER_22: 22 as AddressFamily,
    NUMBER_23: 23 as AddressFamily,
    NUMBER_24: 24 as AddressFamily,
    NUMBER_25: 25 as AddressFamily,
    NUMBER_26: 26 as AddressFamily,
    NUMBER_28: 28 as AddressFamily,
    NUMBER_29: 29 as AddressFamily,
    NUMBER_65536: 65536 as AddressFamily,
    NUMBER_65537: 65537 as AddressFamily,
    NUMBER_MINUS_1: -1 as AddressFamily
};