/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomAttributeData } from './customAttributeData';
import { MethodInfo } from './methodInfo';
import { Module } from './module';
import { SecurityRuleSet } from './securityRuleSet';
import { Type } from './type';
import { TypeInfo } from './typeInfo';

export interface Assembly { 
    readonly definedTypes?: Array<TypeInfo>;
    readonly exportedTypes?: Array<Type>;
    readonly codeBase?: string;
    entryPoint?: MethodInfo;
    readonly fullName?: string;
    readonly imageRuntimeVersion?: string;
    readonly isDynamic?: boolean;
    readonly location?: string;
    readonly reflectionOnly?: boolean;
    readonly isCollectible?: boolean;
    readonly isFullyTrusted?: boolean;
    readonly customAttributes?: Array<CustomAttributeData>;
    readonly escapedCodeBase?: string;
    manifestModule?: Module;
    readonly modules?: Array<Module>;
    readonly globalAssemblyCache?: boolean;
    readonly hostContext?: number;
    securityRuleSet?: SecurityRuleSet;
}