/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActionContextBooleanFunc } from "./actionContextBooleanFunc";
import { BindingSource } from "./bindingSource";
import { IPropertyFilterProvider } from "./iPropertyFilterProvider";
import { Type } from "./type";

export interface BindingInfo {
  bindingSource?: BindingSource;
  binderModelName?: string;
  binderType?: Type;
  propertyFilterProvider?: IPropertyFilterProvider;
  requestPredicate?: ActionContextBooleanFunc;
}
