/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallingConventions } from './callingConventions';
import { CustomAttributeData } from './customAttributeData';
import { MemberTypes } from './memberTypes';
import { MethodBase } from './methodBase';
import { MethodImplAttributes } from './methodImplAttributes';
import { Module } from './module';


export interface ConstructorInfo extends MethodBase { 
    memberType: MemberTypes;
}
