/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActionDescriptor } from './actionDescriptor';
import { AttributeRouteInfo } from './attributeRouteInfo';
import { FilterDescriptor } from './filterDescriptor';
import { IActionConstraintMetadata } from './iActionConstraintMetadata';
import { MethodInfo } from './methodInfo';
import { ParameterDescriptor } from './parameterDescriptor';


export interface ControllerActionDescriptor extends ActionDescriptor { 
    controllerName?: string;
    actionName?: string;
    methodInfo?: MethodInfo;
    controllerTypeInfo?: string;
    displayName?: string;
}
