/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConstructorInfo } from './constructorInfo';
import { CustomAttributeNamedArgument } from './customAttributeNamedArgument';
import { CustomAttributeTypedArgument } from './customAttributeTypedArgument';


export interface CustomAttributeData { 
    attributeType: string;
    constructor: ConstructorInfo;
    constructorArguments: Array<CustomAttributeTypedArgument>;
    namedArguments: Array<CustomAttributeNamedArgument>;
}
