/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EventAttributes = 0 | 512 | 1024;

export const EventAttributes = {
    NUMBER_0: 0 as EventAttributes,
    NUMBER_512: 512 as EventAttributes,
    NUMBER_1024: 1024 as EventAttributes
};