/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MethodBase } from "./methodBase";

export interface Exception {
  targetSite?: MethodBase;
  readonly stackTrace?: string;
  readonly message?: string;
  readonly data?: { [key: string]: any };
  innerException?: Exception;
  helpLink?: string;
  source?: string;
  hResult?: number;
}
