/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type GenericParameterAttributes = 0 | 1 | 2 | 3 | 4 | 8 | 16 | 28;

export const GenericParameterAttributes = {
  NUMBER_0: 0 as GenericParameterAttributes,
  NUMBER_1: 1 as GenericParameterAttributes,
  NUMBER_2: 2 as GenericParameterAttributes,
  NUMBER_3: 3 as GenericParameterAttributes,
  NUMBER_4: 4 as GenericParameterAttributes,
  NUMBER_8: 8 as GenericParameterAttributes,
  NUMBER_16: 16 as GenericParameterAttributes,
  NUMBER_28: 28 as GenericParameterAttributes,
};
