/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HostString } from './hostString';
import { HttpContext } from './httpContext';
import { PathString } from './pathString';
import { PipeReader } from './pipeReader';
import { QueryString } from './queryString';
import { Stream } from './stream';
import { StringStringKeyValuePair } from './stringStringKeyValuePair';
import { StringStringValuesKeyValuePair } from './stringStringValuesKeyValuePair';

export interface HttpRequest {
  httpContext?: HttpContext;
  method?: string;
  scheme?: string;
  isHttps?: boolean;
  host?: HostString;
  pathBase?: PathString;
  path?: PathString;
  queryString?: QueryString;
  query?: Array<StringStringValuesKeyValuePair>;
  protocol?: string;
  readonly headers?: { [key: string]: Array<string> };
  cookies?: Array<StringStringKeyValuePair>;
  contentLength?: number;
  contentType?: string;
  body?: Stream;
  bodyReader?: PipeReader;
  readonly hasFormContentType?: boolean;
  form?: Array<StringStringValuesKeyValuePair>;
  routeValues?: { [key: string]: any };
}
