/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type LayoutKind = 0 | 2 | 3;

export const LayoutKind = {
  NUMBER_0: 0 as LayoutKind,
  NUMBER_2: 2 as LayoutKind,
  NUMBER_3: 3 as LayoutKind,
};
