/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
import { UserLocation } from './userLocation';

export interface Location {
  locationId?: number;
  locationCode?: string;
  locationName?: string;
  locationType?: string;
  locationCountry?: string;
  userFkBirthLocation?: Array<User>;
  userFkResidenceLocation?: Array<User>;
  userLocation?: Array<UserLocation>;
}
