/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type MemberTypes = 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 191;

export const MemberTypes = {
  NUMBER_1: 1 as MemberTypes,
  NUMBER_2: 2 as MemberTypes,
  NUMBER_4: 4 as MemberTypes,
  NUMBER_8: 8 as MemberTypes,
  NUMBER_16: 16 as MemberTypes,
  NUMBER_32: 32 as MemberTypes,
  NUMBER_64: 64 as MemberTypes,
  NUMBER_128: 128 as MemberTypes,
  NUMBER_191: 191 as MemberTypes,
};
