/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ModelValidationState = 0 | 1 | 2 | 3;

export const ModelValidationState = {
  NUMBER_0: 0 as ModelValidationState,
  NUMBER_1: 1 as ModelValidationState,
  NUMBER_2: 2 as ModelValidationState,
  NUMBER_3: 3 as ModelValidationState,
};
