/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type ParameterAttributes = 0 | 1 | 2 | 4 | 8 | 16 | 4096 | 8192 | 16384 | 32768 | 61440;

export const ParameterAttributes = {
    NUMBER_0: 0 as ParameterAttributes,
    NUMBER_1: 1 as ParameterAttributes,
    NUMBER_2: 2 as ParameterAttributes,
    NUMBER_4: 4 as ParameterAttributes,
    NUMBER_8: 8 as ParameterAttributes,
    NUMBER_16: 16 as ParameterAttributes,
    NUMBER_4096: 4096 as ParameterAttributes,
    NUMBER_8192: 8192 as ParameterAttributes,
    NUMBER_16384: 16384 as ParameterAttributes,
    NUMBER_32768: 32768 as ParameterAttributes,
    NUMBER_61440: 61440 as ParameterAttributes
};
