/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomAttributeData } from './customAttributeData';
import { MemberInfo } from './memberInfo';
import { ParameterAttributes } from './parameterAttributes';
import { Type } from './type';

export interface ParameterInfo { 
    attributes?: ParameterAttributes;
    member?: MemberInfo;
    readonly name?: string;
    parameterType?: Type;
    readonly position?: number;
    readonly isIn?: boolean;
    readonly isLcid?: boolean;
    readonly isOptional?: boolean;
    readonly isOut?: boolean;
    readonly isRetval?: boolean;
    readonly defaultValue?: any;
    readonly rawDefaultValue?: any;
    readonly hasDefaultValue?: boolean;
    readonly customAttributes?: Array<CustomAttributeData>;
    readonly metadataToken?: number;
}