/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomAttributeData } from './customAttributeData';
import { MemberInfo } from './memberInfo';
import { MemberTypes } from './memberTypes';
import { MethodInfo } from './methodInfo';
import { Module } from './module';


export interface PropertyInfo extends MemberInfo { 
    memberType: MemberTypes;
    isSpecialName: boolean;
    getMethod?: MethodInfo;
    setMethod?: MethodInfo;
}
