/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PropertyAttributes = 0 | 512 | 1024 | 4096 | 8192 | 16384 | 32768 | 62464;

export const PropertyAttributes = {
    NUMBER_0: 0 as PropertyAttributes,
    NUMBER_512: 512 as PropertyAttributes,
    NUMBER_1024: 1024 as PropertyAttributes,
    NUMBER_4096: 4096 as PropertyAttributes,
    NUMBER_8192: 8192 as PropertyAttributes,
    NUMBER_16384: 16384 as PropertyAttributes,
    NUMBER_32768: 32768 as PropertyAttributes,
    NUMBER_62464: 62464 as PropertyAttributes
};