/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RegisterRequest { 
    email?: string;
    password?: string;
    firstname?: string;
    lastname?: string;
    birthday?: Date;
    title?: string;
    education?: string;
    facebookId?: number;
    birthLocation?: string;
    residenceLocation?: string;
}