/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IEqualityComparerOfString } from './iEqualityComparerOfString';
import { KeyValuePairOfStringAndObject } from './keyValuePairOfStringAndObject';
import { PropertyStorage } from './propertyStorage';


export interface RouteValueDictionary { 
    arrayStorage?: Array<KeyValuePairOfStringAndObject>;
    propertyStorage?: PropertyStorage;
    item?: any;
    comparer?: IEqualityComparerOfString;
    count: number;
    keys?: Array<string>;
    values?: Array<any>;
}
