/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClaimsPrincipal } from "./claimsPrincipal";
import { ControllerContext } from "./controllerContext";
import { HttpContext } from "./httpContext";
import { HttpRequest } from "./httpRequest";
import { HttpResponse } from "./httpResponse";
import { IModelBinderFactory } from "./iModelBinderFactory";
import { IModelMetadataProvider } from "./iModelMetadataProvider";
import { IObjectModelValidator } from "./iObjectModelValidator";
import { IUrlHelper } from "./iUrlHelper";
import { ModelStateEntry } from "./modelStateEntry";
import { ProblemDetailsFactory } from "./problemDetailsFactory";
import { RouteData } from "./routeData";

export interface TagController {
  httpContext?: HttpContext;
  request?: HttpRequest;
  response?: HttpResponse;
  routeData?: RouteData;
  readonly modelState?: { [key: string]: ModelStateEntry };
  controllerContext?: ControllerContext;
  metadataProvider?: IModelMetadataProvider;
  modelBinderFactory?: IModelBinderFactory;
  url?: IUrlHelper;
  objectValidator?: IObjectModelValidator;
  problemDetailsFactory?: ProblemDetailsFactory;
  user?: ClaimsPrincipal;
}
