/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';
import { Post } from './post';
import { UserLocation } from './userLocation';

export interface UserResponse { 
    userId?: string;
    firstname?: string;
    lastname?: string;
    username?: string;
    email?: string;
    birthday?: Date;
    avi?: string;
    facebookId?: number;
    birthLocation?: Location;
    residenceLocation?: Location;
    posts?: Array<Post>;
    followingCount?: number;
    followerCount?: number;
    userLocations?: Array<UserLocation>;
}