/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdentityUser } from './identityUser';
import { Like } from './like';
import { Location } from './location';
import { Post } from './post';
import { PostComment } from './postComment';
import { UserFollowing } from './userFollowing';
import { UserLocation } from './userLocation';
import { UserMessage } from './userMessage';


export interface User extends IdentityUser { 
    firstname?: string;
    lastname?: string;
    birthday?: Date;
    avi?: string;
    fkBirthLocationId?: number;
    fkResidenceLocationId?: number;
    facebookId?: number;
    fkBirthLocation?: Location;
    fkResidenceLocation?: Location;
    like?: Array<Like>;
    post?: Array<Post>;
    postComment?: Array<PostComment>;
    userFollowingFkFollowUser?: Array<UserFollowing>;
    userFollowingFkMainUser?: Array<UserFollowing>;
    userLocation?: Array<UserLocation>;
    userMessageFkRecieverUser?: Array<UserMessage>;
    userMessageFkSenderUser?: Array<UserMessage>;
}
