/**
 * Visit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from "./location";
import { LocationTag } from "./locationTag";
import { PostUserLocation } from "./postUserLocation";
import { User } from "./user";

export interface UserLocation {
  userLocationId?: number;
  fkLocationId?: number;
  fkUserId?: string;
  status?: string;
  city?: string;
  venue?: string;
  fkLocation?: Location;
  fkUser?: User;
  locationTag?: Array<LocationTag>;
  postUserLocation?: Array<PostUserLocation>;
}
