/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from "@angular/core";
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
} from "@angular/common/http";
import { CustomHttpUrlEncodingCodec } from "../encoder";

import { Observable } from "rxjs";

import { UserLocation } from "../model/userLocation";

import { BASE_PATH, COLLECTION_FORMATS } from "../variables";
import { Configuration } from "../configuration";

@Injectable()
export class UserLocationService {
  protected basePath = "https://localhost:5001";
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = "multipart/form-data";
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   *
   *
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userLocationDeleteUserLocation(
    id: number,
    observe?: "body",
    reportProgress?: boolean
  ): Observable<UserLocation>;
  public userLocationDeleteUserLocation(
    id: number,
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<UserLocation>>;
  public userLocationDeleteUserLocation(
    id: number,
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<UserLocation>>;
  public userLocationDeleteUserLocation(
    id: number,
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        "Required parameter id was null or undefined when calling userLocationDeleteUserLocation."
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      "text/plain",
      "application/json",
      "text/json",
    ];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.delete<UserLocation>(
      `${this.basePath}/api/UserLocation/${encodeURIComponent(String(id))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userLocationGetUserLocation(
    id: number,
    observe?: "body",
    reportProgress?: boolean
  ): Observable<UserLocation>;
  public userLocationGetUserLocation(
    id: number,
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<UserLocation>>;
  public userLocationGetUserLocation(
    id: number,
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<UserLocation>>;
  public userLocationGetUserLocation(
    id: number,
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        "Required parameter id was null or undefined when calling userLocationGetUserLocation."
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      "text/plain",
      "application/json",
      "text/json",
    ];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get<UserLocation>(
      `${this.basePath}/api/UserLocation/${encodeURIComponent(String(id))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userLocationGetUserLocationAll(
    observe?: "body",
    reportProgress?: boolean
  ): Observable<Array<UserLocation>>;
  public userLocationGetUserLocationAll(
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<Array<UserLocation>>>;
  public userLocationGetUserLocationAll(
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<Array<UserLocation>>>;
  public userLocationGetUserLocationAll(
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      "text/plain",
      "application/json",
      "text/json",
    ];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get<Array<UserLocation>>(
      `${this.basePath}/api/UserLocation`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param userLocation
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userLocationPostUserLocation(
    userLocation: UserLocation,
    observe?: "body",
    reportProgress?: boolean
  ): Observable<UserLocation>;
  public userLocationPostUserLocation(
    userLocation: UserLocation,
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<UserLocation>>;
  public userLocationPostUserLocation(
    userLocation: UserLocation,
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<UserLocation>>;
  public userLocationPostUserLocation(
    userLocation: UserLocation,
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    if (userLocation === null || userLocation === undefined) {
      throw new Error(
        "Required parameter userLocation was null or undefined when calling userLocationPostUserLocation."
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      "text/plain",
      "application/json",
      "text/json",
    ];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      "application/json-patch+json",
      "application/json",
      "text/json",
      "application/_*+json",
    ];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set("Content-Type", httpContentTypeSelected);
    }

    return this.httpClient.post<UserLocation>(
      `${this.basePath}/api/UserLocation`,
      userLocation,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param id
   * @param userLocation
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userLocationPutUserLocation(
    id: number,
    userLocation: UserLocation,
    observe?: "body",
    reportProgress?: boolean
  ): Observable<Blob>;
  public userLocationPutUserLocation(
    id: number,
    userLocation: UserLocation,
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<Blob>>;
  public userLocationPutUserLocation(
    id: number,
    userLocation: UserLocation,
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<Blob>>;
  public userLocationPutUserLocation(
    id: number,
    userLocation: UserLocation,
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        "Required parameter id was null or undefined when calling userLocationPutUserLocation."
      );
    }

    if (userLocation === null || userLocation === undefined) {
      throw new Error(
        "Required parameter userLocation was null or undefined when calling userLocationPutUserLocation."
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      "application/json-patch+json",
      "application/json",
      "text/json",
      "application/_*+json",
    ];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set("Content-Type", httpContentTypeSelected);
    }

    return this.httpClient.put(
      `${this.basePath}/api/UserLocation/${encodeURIComponent(String(id))}`,
      userLocation,
      {
        responseType: "blob",
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
